Livraison/urls.py
from django.urls import path
from . import views

app_name='Livraison'
urlpatterns = [
    path('', views.login, name="login"),
    path('menu/', views.menu, name='menu'),  # Assurez-vous que le nom est unique
    path('add_Livraison/', views.add_Livraison, name='add_Livraison'),
    path('ajouter_Livraison/', views.ajouter_Livraison, name='ajouter_Livraison'),
    path('delete/<int:id>/', views.Livraison_del, name='Livraison_del'), 
    path('Livraison/confirm_del/', views.delete_Livraison, name='delete_Livraison'),
    path('editer/<int:id>/', views.Livraison_edit, name='Livraison_edit'),
    path('edit/<int:id>/', views.edit_Livraison, name='edit_Livraison'), 
    
]

app_utilisateur/urls.py
from django.urls import path
from . import views

app_name = 'app_utilisateur'

urlpatterns = [
    path('', views.login, name="login"),
    path('user/', views.connexion_view, name='user'),
    path('menu/', views.menu, name='menu'),
    path('index/', views.index, name='index'),
    path('utilisateurs/', views.menu, name='utilisateurs'),  # Assurez-vous que la vue correspondante est définie.
    path('user/add/', views.add_user, name='add_user'),
    path('ajouter_user/', views.ajouter_user, name='ajouter_user'),
    path('delete/<int:id>/', views.user_del, name='user_del'), 
    path('user/confirm_del/', views.delete_user, name='delete_user'),
    path('editer/<int:id>/', views.user_edit, name='user_edit'),
    path('profil/', views.profil, name='profil'),
    path('edit/<int:id>/', views.edit_user, name='edit_user'),
    
]

colis/urls.py
from django.urls import path
from . import views

app_name='colis'
urlpatterns = [
    path('', views.login, name="login"),
    path('menu/', views.menu, name='menu'),  # Assurez-vous que le nom est unique
    path('add_colis/', views.add_colis, name='add_colis'),
    path('ajouter_colis/', views.ajouter_colis, name='ajouter_colis'),
    path('delete/<int:id>/', views.colis_del, name='colis_del'), 
    path('colis/confirm_del/', views.delete_colis, name='delete_colis'),
    path('editer/<int:id>/', views.colis_edit, name='colis_edit'),
    path('edit/<int:id>/', views.edit_colis, name='edit_colis'), 
    
]

perso_admin/urls.py
from django.urls import path
from . import views

app_name='perso_admin'
urlpatterns = [
    path('', views.login, name="login"),
    path('Admin/', views.connexion_view, name='Admin'),
    path('menu/', views.menu, name='menu'),  # Assurez-vous que le nom est unique
    path('dashboard/', views.dashboard, name='dashboard'),
    path('Admin/add_admin/', views.add_admin, name='add_admin'),
    path('ajouter_admin/', views.ajouter_admin, name='ajouter_admin'),
    path('delete/<int:id>/', views.admin_del, name='admin_del'), 
    path('admin/confirm_del/', views.delete_admin, name='delete_admin'),
    path('editer/<int:id>/', views.admin_edit, name='admin_edit'),
    path('edit/<int:id>/', views.edit_admin, name='edit_admin'), 
    path('logout/', views.logout, name='logout'),

    
]

suivi_livraison/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('root/', admin.site.urls),
    path('admin/', include('perso_admin.urls')),
    path('utilisateurs/', include('app_utilisateur.urls')),
    path('colis/', include('colis.urls')),
    path('Livraison/', include('Livraison.urls')),
    path('api/', include('app_utilisateur.api_urls')),

    
]

Livraison/models.py
from django.db import models
from colis.models import Colis
from app_utilisateur.models import Utilisateur
from django.core.exceptions import ObjectDoesNotExist


class StatutLivraison(models.TextChoices):
    EN_TRANSIT = 'in_transit', 'En Transit'
    LIVRE = 'delivered', 'Livré'
    RETARDE = 'delayed', 'Retardé'

class Livraison(models.Model):
    colis = models.OneToOneField(Colis, on_delete=models.CASCADE)
    statut = models.CharField(max_length=20, choices=StatutLivraison.choices, default=StatutLivraison.EN_TRANSIT)
    date_derniere_mise_a_jour = models.DateTimeField(auto_now=True)
    proprietaire=models.ForeignKey(Utilisateur, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.colis.numero_suivi} - {self.statut}"

    @staticmethod
    def ajouter_livraison(colis, destinataire, statut):
        """
        Ajoute un nouveau livraison à la base de données.
        """
        livraison = Livraison(
            colis=colis,
            proprietaire=destinataire,
            statut=statut
        )
        livraison.save()
        return livraison

    def modifier_livraison(self, expediteur=None, destinataire=None, adresse=None):
        """
        Modifie les informations du livraison existant.
        """
        if expediteur:
            self.expediteur = expediteur
        if destinataire:
            self.destinataire = destinataire
        if adresse:
            self.adresse = adresse
        self.save()
        return self

    def supprimer_livraison(self):
        """
        Supprime le livraison de la base de données.
        """
        self.delete()
        return f"livraison {self.id} supprimé avec succès."

    @staticmethod
    def consulter_livraison(id):
        """
        Consulter un livraison par son numéro de suivi.
        """
        try:
            livraison = Livraison.objects.get(id=id)
            return livraison
        except ObjectDoesNotExist:
            return None

Livraison/templates/Livraison/models.py
from django.db import models
from colis.models import Colis
from app_utilisateur.models import Utilisateur
from django.core.exceptions import ObjectDoesNotExist


class StatutLivraison(models.TextChoices):
    EN_TRANSIT = 'in_transit', 'En Transit'
    LIVRE = 'delivered', 'Livré'
    RETARDE = 'delayed', 'Retardé'

class Livraison(models.Model):
    colis = models.OneToOneField(Colis, on_delete=models.CASCADE)
    statut = models.CharField(max_length=20, choices=StatutLivraison.choices, default=StatutLivraison.EN_TRANSIT)
    date_derniere_mise_a_jour = models.DateTimeField(auto_now=True)
    proprietaire=models.ForeignKey(Utilisateur, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.colis.numero_suivi} - {self.statut}"

    @staticmethod
    def ajouter_livraison(colis, destinataire, statut):
        """
        Ajoute un nouveau livraison à la base de données.
        """
        livraison = Livraison(
            colis=colis,
            proprietaire=destinataire,
            statut=statut
        )
        livraison.save()
        return livraison

    def modifier_livraison(self, expediteur=None, destinataire=None, adresse=None):
        """
        Modifie les informations du livraison existant.
        """
        if expediteur:
            self.expediteur = expediteur
        if destinataire:
            self.destinataire = destinataire
        if adresse:
            self.adresse = adresse
        self.save()
        return self

    def supprimer_livraison(self):
        """
        Supprime le livraison de la base de données.
        """
        self.delete()
        return f"livraison {self.id} supprimé avec succès."

    @staticmethod
    def consulter_livraison(id):
        """
        Consulter un livraison par son numéro de suivi.
        """
        try:
            livraison = Livraison.objects.get(id=id)
            return livraison
        except ObjectDoesNotExist:
            return None

Livraison/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse
from .models import Livraison
from colis.models import Colis
from app_utilisateur.models import Utilisateur
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth.hashers import check_password, make_password


def add_Livraison(request):
    liste= Utilisateur.objects.all()
    colis=Colis.objects.all()
    return render(request, "Livraison/add_Livraison.html",{'liste':liste, 'colis':colis})
def ajouter_Livraison(request):
    livraison= Livraison.objects.all()
    if request.method == 'POST':
        # Récupération des données du formulaire
        colis_id = request.POST.get('colis')
        statut = request.POST.get('statut')
        destinataire_id = request.POST.get('destinataire')
    
 
        destinataire = get_object_or_404(Utilisateur, id=destinataire_id)
        colis = get_object_or_404(Colis, id=colis_id)

        new_Livraison = Livraison(colis=colis, statut=statut, proprietaire=destinataire)

        # Sauvegarde de l'Livraisonistrateur dans la base de données
        new_Livraison.save()

        # Redirection après la sauvegarde
        return redirect('Livraison:menu')  # Utilisez le nom de la vue défini dans `urls.py`

    return render(request, 'Livraison/add_Livraison.html', {'liste':Livraison})
def Livraison_del(request, id):
    livraison = get_object_or_404(Livraison, id=id)
    return render(request, "Livraison/delete_Livraison.html", {"Livraison": livraison})

def Livraison_edit(request, id):
    liste= Utilisateur.objects.all()
    colis=Colis.objects.all()
    livraison = get_object_or_404(Livraison, id=id)
    return render(request, "Livraison/edit_Livraison.html", {"Livraison": livraison,'liste':liste, 'colis':colis})

# views.py

def edit_Livraison(request, id):
    
    utilisateurs= Livraison.objects.all()
    livraison = get_object_or_404(Livraison, id=id)  # Récupération de l'Livraisonistrateur via son ID

    if request.method == 'POST':
        # Mettre à jour les informations de l'Livraisonistrateur
        colis_id = request.POST.get('colis')
        livraison.statut = request.POST.get('statut')
        destinataire_id = request.POST.get('destinataire')
    
 
        livraison.destinataire = get_object_or_404(Utilisateur, id=destinataire_id)
        livraison.colis = get_object_or_404(Colis, id=colis_id)

  # Assurez-vous que le modèle gère la modification du mot de passe de cette manière

        livraison.save()  # Sauvegarde les modifications
        return redirect(reverse('Livraison:menu'))  # Redirige vers une liste d'Livraison ou autre page

    
    return render(request, 'Livraison/menu.html', {"liste":utilisateurs})

def delete_Livraison(request):
    if request.method == "POST":
        id = request.POST.get('Livraison_id')  # Récupérer l'ID du formulaire
        livraison = get_object_or_404(Livraison, id=id)
        livraison.delete()  # Supprime l'Livraisonistrateur
        messages.success(request, "Livraison supprimé avec succès.")  # Message de confirmation
        return redirect('/Livraison/menu/')  # Redirige vers le menu ou une autre page
    return redirect('/Livraison/menu/')   



def menu(request):
    username = request.session.get('username')
    email = request.session.get('email')
    utilisateurs= Livraison.objects.all()
    nombre=utilisateurs.count()
    context={'username':username,'email':email, "liste":utilisateurs,"nombre":nombre}
    return render(request, 'Livraison/menu.html', context)
     

Livraison/templates/Livraison/add_Livraison.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title></title>
  <link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <link href="{% static 'Livraison/elements/css/nucleo-icons.css'%}" rel="stylesheet" />
  <link href="{% static 'Livraison/elements/css/nucleo-svg.css'%}" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <link id="pagestyle" href="{% static 'Livraison/elements/css/material-dashboard.css'%}" rel="stylesheet" />
  <script src="{% static 'Livraison/js/jquery.min.js'%}"></script>
  <script src="{% static 'Livraison/js/script.js'%}"></script>
  <link rel="stylesheet" href="{% static 'Livraison/css/style.css'%}">
  <link rel="stylesheet" href="{% static 'Livraison/css/all.min.css'%}">
  <script src="{% static 'Livraison/js/all.min.js'%}"></script>
  <script src="{% static 'Livraison/js/slim.min.js'%}"></script>
  <script src="{% static 'Livraison/js/popper.min.js'%}"></script>
  <link rel="stylesheet" href="{% static 'Livraison/css/bootstrap.min.css'%}">
  <script src="{% static 'Livraison/js/bootstrap.min.js'%}"></script>
</head>

<body class="g-sidenav-show bg-gray-100">
  <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
        <span class="ms-1 font-weight-bold text-white">Suivi Livraison.</span><i class="fas fa-paper-plane bg-white rounded-pill p-2 mx-3 " style="font-size: 20px; color: red; position: relative; top: 10px;"></i>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse w-auto" id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'perso_admin:dashboard' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-chart-line"></span>
            </div>
            <span class="nav-link-text ms-1">Tableau de bord</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'app_utilisateur:profil' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-user-circle"></span>
            </div>
            <span class="nav-link-text ms-1">Mon profil</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'perso_admin:menu'%}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-people-group"></span>
            </div>
            <span class="nav-link-text ms-1">Administrateurs</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'colis:menu'%}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-cube"></span>
            </div>
            <span class="nav-link-text ms-1">Colis</span>
          </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'Livraison:menu' %}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <span class="fas fa-truck-fast"></span>
              </div>
              <span class="nav-link-text ms-1">Livraisons</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'app_utilisateur:menu' %}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <span class="fas fa-users"></span>
              </div>
              <span class="nav-link-text ms-1">Utilisateurs</span>
            </a>
          </li>
        <div style="border-top: 1px solid white;"></div>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'perso_admin:logout' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-power-off"></span>
            </div>
            <span class="nav-link-text ms-1">Deconnexion</span>
          </a>
        </li>
      </ul>
    </div>
  </aside>  
  <main class="main-content border-radius-lg">
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur"
      data-scroll="true">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark font-weight-bolder" aria-current="page">Ajout d'Administrateur</li>
          </ol>
          <h6 class="font-weight-bolder mb-0">Ajouter des Administrateurs</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <div class="input-group input-group-outline">
              <input type="text" class="form-control" id="searchInput" placeholder="Recherche">
            </div>
          </div>
          <ul class="navbar-nav justify-content-end">
            <li class="nav-item d-flex align-items-center">
              <a class="btn btn-outline-primary btn-sm mb-0 me-3" href="{% url 'app_utilisateur:profil'%}" data-toggle="tooltip" data-placement="bottom" title="Mon profil"> <span class="fas fa-user-circle"></span></a>
            </li>
            <li class="nav-item d-flex align-items-center">
              <a class="btn btn-outline-primary btn-sm mb-0 me-3" href="{% url 'perso_admin:logout'%}" data-toggle="tooltip" data-placement="bottom" title="Se deconnecter"> <span class="fas fa-power-off"></span></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid py-4">
      <div class="row">
        <div class="container ">
          <div class="row mb-3">
            <div class="col-md-6">
              <div class="d-flex flex-column justify-content-center">
                <h1 class="mb-0 text-sm"> Ajout
                </h1>
                <p class="text-xs text-secondary mb-0">
                  
                </p>
              </div>
            </div>
            <div class="col-md-6">
              <p class="text-xs font-weight-bold mb-0">
              </p>

            </div>
          </div>
          <div class="col-12">
            <div class="card mb-4">
              <div class="card-header pb-0">
                <h6>Ajouter des Livraison</h6>
              </div>
              <div class="card-body px-0 pt-0 pb-2">
                <form class="mx-3" method="post" action="{% url 'Livraison:ajouter_Livraison' %}">
                  <div class="form-group" style="height: 16px;">
                    {% if messages %}
                    {% for message in messages %}
                        <p class="text-danger" style="font-size: 13px; font-weight: bold;">{{ message }} <span class="fas fa-circle-exclamation"></span></p>
                      {% endfor %}
                  {% endif %}
                  </div>          
                  <div class="form-group my-1">
                    <label for="colis" class="my-0">Colis</label>
                    <select name="colis" id="colis" class="form-control">
                      {% for coli in colis %}
                      <option value="{{ coli.id }}">{{ coli.expediteur}}</option>
                      {% endfor %}
                    </select>
                    <div class="form-group my-1">
                      <label for="statut" class="my-0">statut</label>
                      <select name="statut" id="statut" class="form-control">
                        <option value="in_transit">En Transit</option>
                        <option value="delivered">Livré</option>
                        <option value="delayed">Retardé</option>
                      </select>
                  <div class="form-group my-1">
                    <label for="destinataire" class="my-0">destinataire</label>
                    <select name="destinataire" id="destinataire" class="form-control">
                      {% for utilisateurs in liste %}
                      <option value="{{ utilisateurs.id }}">{{ utilisateurs.username}}</option>
                      {% endfor %}
                    </select>
                  </div>

                  <button type="submit" class="btn btn-primary my-1 form-control">Enregistrer <span
                      class="fas fa-save mx-3"></span></button>
                </form>
                <div id="paginationE" class="mt-3 mx-3">
                  <span class="px-3" id="pagination"></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <script src="{% static 'Livraison/js/script.js'%}">


  </script>
  <!-- Edit Admin Modal -->
  <div class="modal fade" id="editAdminModal" tabindex="-1" role="dialog" aria-labelledby="editAdminModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editAdminModalLabel">Consulter un Administrateur</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  </div>

</body>

</html>

Livraison/templates/Livraison/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'perso_admin/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'perso_admin/assets/fonts/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'perso_admin/assets/css/style.css' %}" rel="stylesheet">
    <link rel="icon" type="image/png" href="{% static 'perso_admin/images/fav32.png' %}">
    <link rel="stylesheet" href="{% static 'perso_admin/css/all.min.css' %}">
    <script src="{% static 'perso_admin/js/all.min.js' %}"></script>
    <title>Page de connexion</title>
</head>
<body>
<section class="form-08">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form class="_form-08-main" method="post" action="{% url 'perso_admin:Admin' %}">
                    {% csrf_token %}
                    <div class="_form-08-head">
                        <span class="fas fa-circle-user" style="color: rgb(0, 64, 240); font-size: 50px;"></span>
                        <h2>Veuillez entrer vos informations</h2>
                    </div>
                    <div class="form-group">
                        <label>Votre Email <span class="mx-1 fas fa-envelope"></span></label>
                        <input type="email" name="email" class="form-control rounded" placeholder="votre Email">
                    </div>
                    <div class="form-group my-0 py-0">
                        <label>Mot de passe <span class="mx-1 fas fa-lock"></span></label>
                        <input type="password" name="password" class="form-control rounded-pill" placeholder="votre Password">
                    </div>
                    <div class="form-group" style="height: 16px;">
                            {% if messages %}
                            {% for message in messages %}
                                <p class="text-danger" style="font-size: 13px; font-weight: bold;">{{ message }} <span class="fas fa-circle-exclamation"></span></p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group mt-2">
                        <button class="form-control btn btn-success rounded-pill" type="submit">Se connecter <span class="fas fa-arrow-right-from-bracket mx-2"></span></button>
                    </div>
                </form>
                
            </div>
        </div>
    </div>
</section>
<script src="static 'perso_admin/js/all.min.js"></script>
<script src="static 'perso_admin/js/bootstrap.min.js"></script>
</body>
</html>