Livraison/urls.py
from django.urls import path
from . import views

app_name='Livraison'
urlpatterns = [
    path('', views.login, name="login"),
    path('menu/', views.menu, name='menu'),  # Assurez-vous que le nom est unique
    path('add_Livraison/', views.add_Livraison, name='add_Livraison'),
    path('ajouter_Livraison/', views.ajouter_Livraison, name='ajouter_Livraison'),
    path('delete/<int:id>/', views.Livraison_del, name='Livraison_del'), 
    path('Livraison/confirm_del/', views.delete_Livraison, name='delete_Livraison'),
    path('editer/<int:id>/', views.Livraison_edit, name='Livraison_edit'),
    path('edit/<int:id>/', views.edit_Livraison, name='edit_Livraison'), 
    
]

app_utilisateur/urls.py
from django.urls import path
from . import views

app_name = 'app_utilisateur'

urlpatterns = [
    path('', views.login, name="login"),
    path('user/', views.connexion_view, name='user'),
    path('menu/', views.menu, name='menu'),
    path('index/', views.index, name='index'),
    path('utilisateurs/', views.menu, name='utilisateurs'),  # Assurez-vous que la vue correspondante est définie.
    path('user/add/', views.add_user, name='add_user'),
    path('ajouter_user/', views.ajouter_user, name='ajouter_user'),
    path('delete/<int:id>/', views.user_del, name='user_del'), 
    path('user/confirm_del/', views.delete_user, name='delete_user'),
    path('editer/<int:id>/', views.user_edit, name='user_edit'),
    path('profil/', views.profil, name='profil'),
    path('edit/<int:id>/', views.edit_user, name='edit_user'),
    
]

colis/urls.py
from django.urls import path
from . import views

app_name='colis'
urlpatterns = [
    path('', views.login, name="login"),
    path('menu/', views.menu, name='menu'),  # Assurez-vous que le nom est unique
    path('add_colis/', views.add_colis, name='add_colis'),
    path('ajouter_colis/', views.ajouter_colis, name='ajouter_colis'),
    path('delete/<int:id>/', views.colis_del, name='colis_del'), 
    path('colis/confirm_del/', views.delete_colis, name='delete_colis'),
    path('editer/<int:id>/', views.colis_edit, name='colis_edit'),
    path('edit/<int:id>/', views.edit_colis, name='edit_colis'), 
    
]

perso_admin/urls.py
from django.urls import path
from . import views

app_name='perso_admin'
urlpatterns = [
    path('', views.login, name="login"),
    path('Admin/', views.connexion_view, name='Admin'),
    path('menu/', views.menu, name='menu'),  # Assurez-vous que le nom est unique
    path('dashboard/', views.dashboard, name='dashboard'),
    path('Admin/add_admin/', views.add_admin, name='add_admin'),
    path('ajouter_admin/', views.ajouter_admin, name='ajouter_admin'),
    path('delete/<int:id>/', views.admin_del, name='admin_del'), 
    path('admin/confirm_del/', views.delete_admin, name='delete_admin'),
    path('editer/<int:id>/', views.admin_edit, name='admin_edit'),
    path('edit/<int:id>/', views.edit_admin, name='edit_admin'), 
    path('logout/', views.logout, name='logout'),

    
]

suivi_livraison/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('root/', admin.site.urls),
    path('admin/', include('perso_admin.urls')),
    path('utilisateurs/', include('app_utilisateur.urls')),
    path('colis/', include('colis.urls')),
    path('Livraison/', include('Livraison.urls')),
    path('api/', include('app_utilisateur.api_urls')),

    
]

perso_admin/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.hashers import make_password


class Admin(models.Model):
    date_creation = models.DateTimeField(auto_now_add=True)
    email=models.EmailField()
    mot_de_passe=models.CharField(max_length=50)
    username=models.CharField(max_length=50)

    
    def __str__(self) -> str:
        return self.username
    

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        
    def inscrire(self):
        # Logique pour inscrire un nouvel utilisateur
        pass

    def se_connecter(self):
        # Logique pour se connecter
        pass

    def mettre_a_jour_profil(self):
        # Logique pour mettre à jour le profil de l'utilisateur
        pass

perso_admin/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse
from .models import Admin
from colis.models import Colis
from Livraison.models import Livraison
from app_utilisateur.models import Utilisateur
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth.hashers import check_password, make_password

def add_admin(request):
    return render(request, "perso_admin/add_admin.html")
def ajouter_admin(request):
    Administrateurs= Admin.objects.all()
    if request.method == 'POST':
        # Récupération des données du formulaire
        admin_name = request.POST.get('adminName')
        admin_email = request.POST.get('adminEmail')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
    
        if Admin.objects.filter(email=admin_email).exists():
            messages.error(request, 'l\'email existe déja')
            return render(request, 'perso_admin/add_admin.html', {'error': "L'email existe déja."})
        # Validation de la correspondance des mots de passe
        if password1 != password2:
            return render(request, 'perso_admin/add_admin.html', {'error': "Les mots de passe ne correspondent pas."})

        # Hachage du mot de passe
        hashed_password = make_password(password1)

        # Création d'une instance de l'administrateur avec les données fournies
        new_admin = Admin(username=admin_name, email=admin_email, mot_de_passe=hashed_password)

        # Sauvegarde de l'administrateur dans la base de données
        new_admin.save()

        # Redirection après la sauvegarde
        return redirect('perso_admin:menu')  # Utilisez le nom de la vue défini dans `urls.py`

    return render(request, 'perso_admin/add_admin.html', {'liste':Administrateurs})
def admin_del(request, id):
    admin = get_object_or_404(Admin, id=id)
    return render(request, "perso_admin/delete_admin.html", {"admin": admin})

def dashboard(request):
    administrateurs= Admin.objects.all()
    utilisateurs= Utilisateur.objects.all()
    colis= Colis.objects.all()
    livraison= Livraison.objects.all()
    nb_admin=administrateurs.count()
    nb_user=utilisateurs.count()
    nb_colis=colis.count()
    nb_livraison=livraison.count()
    donnees={'administrateurs':administrateurs,"utilisateurs":utilisateurs,'colis':colis,"livraison":livraison, 'nb_admin':nb_admin ,'nb_user':nb_user,"nb_colis":nb_colis,'nb_livraison':nb_livraison}
    return render(request, "perso_admin/dashboard.html", donnees)
def admin_edit(request, id):
    admin = get_object_or_404(Admin, id=id)
    return render(request, "perso_admin/edit_admin.html", {"admin": admin})

# views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Admin  # Assurez-vous que ce modèle existe et contient les champs appropriés
from django.urls import reverse

def edit_admin(request, id):
    utilisateurs= Admin.objects.all()
    admin = get_object_or_404(Admin, id=id)  # Récupération de l'administrateur via son ID

    if request.method == 'POST':
        # Mettre à jour les informations de l'administrateur
        admin.username = request.POST.get('adminName')
        admin.email = request.POST.get('adminEmail')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        if password1 and password1 == password2:
            admin.mot_de_passe=make_password(password1)  # Assurez-vous que le modèle gère la modification du mot de passe de cette manière

        admin.save()  # Sauvegarde les modifications
        return redirect(reverse('perso_admin:menu'))  # Redirige vers une liste d'admin ou autre page

    
    return render(request, 'perso_admin/menu.html', {"liste":utilisateurs})

def delete_admin(request):
    if request.method == "POST":
        id = request.POST.get('admin_id')  # Récupérer l'ID du formulaire
        admin = get_object_or_404(Admin, id=id)
        admin.delete()  # Supprime l'administrateur
        messages.success(request, "Administrateur supprimé avec succès.")  # Message de confirmation
        return redirect('/admin/menu/')  # Redirige vers le menu ou une autre page
    return redirect('/admin/menu/')   
def login(request):
    Administrateurs= Admin.objects.all()
    return render(request, "perso_admin/login.html", {'administrateurs':Administrateurs})



def menu(request):
    username = request.session.get('username')
    email = request.session.get('email')
    utilisateurs= Admin.objects.all()
    nombre=utilisateurs.count()
    context={'username':username,'email':email, "liste":utilisateurs,"nombre":nombre}
    return render(request, 'perso_admin/menu.html', context)
     
def logout(request):
    request.session.flush()    
    return redirect(reverse("perso_admin:login"))

def connexion_view(request):
    Administrateurs= Admin.objects.all()
    nombre=Administrateurs.count()

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        try:
            administrateur = Admin.objects.get(email=email)
        except Admin.DoesNotExist:
           messages.error(request, 'Email n\'existe pas') 
           return render(request, 'perso_admin/login.html')
        if administrateur is not None:
            if check_password(password, administrateur.mot_de_passe):
                request.session['username'] = administrateur.username
                request.session['email'] = administrateur.email
                request.session['nombre'] = nombre
                
                return redirect("perso_admin:menu")
            else:
                messages.error(request, 'mot de passe incorrect')
    return render(request, 'perso_admin/login.html')


@login_required
def dashboard_view(request):
    return render(request, 'menu.html')

def ajouter_colis_view(request):
    if request.method == 'POST':
        numero_suivi = request.POST['numero_suivi']
        expediteur = request.POST['expediteur']
        destinataire = request.POST['destinataire']
        adresse = request.POST['adresse']
        Colis.ajouter_colis(numero_suivi, expediteur, destinataire, adresse)
        return redirect('colis_list')

    return render(request, 'ajouter_colis.html')

def modifier_colis_view(request, numero_suivi):
    colis = Colis.consulter_colis(numero_suivi)
    if request.method == 'POST':
        expediteur = request.POST['expediteur']
        destinataire = request.POST['destinataire']
        adresse = request.POST['adresse']
        colis.modifier_colis(expediteur, destinataire, adresse)
        return redirect('colis_detail', numero_suivi=colis.numero_suivi)

    return render(request, 'modifier_colis.html', {'colis': colis})

def supprimer_colis_view(request, numero_suivi):
    colis = Colis.consulter_colis(numero_suivi)
    if colis:
        colis.supprimer_colis()
    return redirect('colis_list')

perso_admin/templates/perso_admin/add_admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title></title>
  <link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <link href="{% static 'perso_admin/elements/css/nucleo-icons.css'%}" rel="stylesheet" />
  <link href="{% static 'perso_admin/elements/css/nucleo-svg.css'%}" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <link id="pagestyle" href="{% static 'perso_admin/elements/css/material-dashboard.css'%}" rel="stylesheet" />
  <script src="{% static 'perso_admin/js/jquery.min.js'%}"></script>
  <script src="{% static 'perso_admin/js/script.js'%}"></script>
  <link rel="stylesheet" href="{% static 'perso_admin/css/style.css'%}">
  <link rel="stylesheet" href="{% static 'perso_admin/css/all.min.css'%}">
  <script src="{% static 'perso_admin/js/all.min.js'%}"></script>
  <script src="{% static 'perso_admin/js/slim.min.js'%}"></script>
  <script src="{% static 'perso_admin/js/popper.min.js'%}"></script>
  <link rel="stylesheet" href="{% static 'perso_admin/css/bootstrap.min.css'%}">
  <script src="{% static 'perso_admin/js/bootstrap.min.js'%}"></script>
</head>

<body class="g-sidenav-show bg-gray-100">
  <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
        <span class="ms-1 font-weight-bold text-white">Suivi Livraison.</span><i class="fas fa-paper-plane bg-white rounded-pill p-2 mx-3 " style="font-size: 20px; color: red; position: relative; top: 10px;"></i>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse w-auto" id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'perso_admin:dashboard' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-chart-line"></span>
            </div>
            <span class="nav-link-text ms-1">Tableau de bord</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'app_utilisateur:profil' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-user-circle"></span>
            </div>
            <span class="nav-link-text ms-1">Mon profil</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'perso_admin:menu'%}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-people-group"></span>
            </div>
            <span class="nav-link-text ms-1">Administrateurs</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'colis:menu'%}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-cube"></span>
            </div>
            <span class="nav-link-text ms-1">Colis</span>
          </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'Livraison:menu' %}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <span class="fas fa-truck-fast"></span>
              </div>
              <span class="nav-link-text ms-1">Livraisons</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'app_utilisateur:menu' %}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <span class="fas fa-users"></span>
              </div>
              <span class="nav-link-text ms-1">Utilisateurs</span>
            </a>
          </li>
        <div style="border-top: 1px solid white;"></div>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'perso_admin:logout' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-power-off"></span>
            </div>
            <span class="nav-link-text ms-1">Deconnexion</span>
          </a>
        </li>
      </ul>
    </div>
  </aside>  
  <main class="main-content border-radius-lg">
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur"
      data-scroll="true">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark font-weight-bolder" aria-current="page">Ajout d'Administrateur</li>
          </ol>
          <h6 class="font-weight-bolder mb-0">Ajouter des Administrateurs</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <div class="input-group input-group-outline">
              <input type="text" class="form-control" id="searchInput" placeholder="Recherche">
            </div>
          </div>
          <ul class="navbar-nav justify-content-end">
            <li class="nav-item d-flex align-items-center">
              <a class="btn btn-outline-primary btn-sm mb-0 me-3" href="{% url 'app_utilisateur:profil'%}" data-toggle="tooltip" data-placement="bottom" title="Mon profil"> <span class="fas fa-user-circle"></span></a>
            </li>
            <li class="nav-item d-flex align-items-center">
              <a class="btn btn-outline-primary btn-sm mb-0 me-3" href="{% url 'perso_admin:logout'%}" data-toggle="tooltip" data-placement="bottom" title="Se deconnecter"> <span class="fas fa-power-off"></span></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid py-4">
      <div class="row">
        <div class="container ">
          <div class="row mb-3">
            <div class="col-md-6">
              <div class="d-flex flex-column justify-content-center">
                <h1 class="mb-0 text-sm"> Ajout
                </h1>
                <p class="text-xs text-secondary mb-0">
                  
                </p>
              </div>
            </div>
            <div class="col-md-6">
              <p class="text-xs font-weight-bold mb-0">
              </p>

            </div>
          </div>
          <div class="col-12">
            <div class="card mb-4">
              <div class="card-header pb-0">
                <h6>Ajouter des administrateurs</h6>
              </div>
              <div class="card-body px-0 pt-0 pb-2">
                <form class="mx-3" method="post" action="{% url 'perso_admin:ajouter_admin' %}">
                  <div class="form-group" style="height: 16px;">
                    {% if messages %}
                    {% for message in messages %}
                        <p class="text-danger" style="font-size: 13px; font-weight: bold;">{{ message }} <span class="fas fa-circle-exclamation"></span></p>
                      {% endfor %}
                  {% endif %}
                  </div>          
                  <div class="form-group my-1">
                    <label for="adminName" class="my-0">Nom</label>
                    <input type="text" class="form-control" id="adminName" name="adminName" required>
                  </div>
                  <div class="form-group my-1">
                    <label for="adminEmail" class="my-0">Email</label>
                    <input type="email" class="form-control" id="adminEmail" name="adminEmail" required>
                  </div>

                  <div class="form-group my-1">
                    <label for="password1" class="my-0">Mot de passe</label>
                    <input type="password" class="form-control" id="password1" name="password1">
                  </div>
                  <div class="form-group my-1">
                    <label for="password2" class="my-0">Confirmer mot de passe</label>
                    <input type="password" class="form-control" id="password2" name="password2">
                  </div>

                  <button type="submit" class="btn btn-primary my-1 form-control">Enregistrer <span
                      class="fas fa-save mx-3"></span></button>
                </form>
                <div id="paginationE" class="mt-3 mx-3">
                  <span class="px-3" id="pagination"></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <script src="{% static 'perso_admin/js/script.js'%}">


  </script>
  <!-- Edit Admin Modal -->
  <div class="modal fade" id="editAdminModal" tabindex="-1" role="dialog" aria-labelledby="editAdminModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editAdminModalLabel">Consulter un Administrateur</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  </div>

</body>

</html>

perso_admin/templates/perso_admin/delete_admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title></title>
  <link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <link href="{% static 'perso_admin/elements/css/nucleo-icons.css'%}" rel="stylesheet" />
  <link href="{% static 'perso_admin/elements/css/nucleo-svg.css'%}" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <link id="pagestyle" href="{% static 'perso_admin/elements/css/material-dashboard.css'%}" rel="stylesheet" />
  <script src="{% static 'perso_admin/js/jquery.min.js'%}"></script>
  <script src="{% static 'perso_admin/js/script.js'%}"></script>
  <link rel="stylesheet" href="{% static 'perso_admin/css/style.css'%}">
  <link rel="stylesheet" href="{% static 'perso_admin/css/all.min.css'%}">
  <script src="{% static 'perso_admin/js/all.min.js'%}"></script>
  <script src="{% static 'perso_admin/js/slim.min.js'%}"></script>
  <script src="{% static 'perso_admin/js/popper.min.js'%}"></script>
  <link rel="stylesheet" href="{% static 'perso_admin/css/bootstrap.min.css'%}">
  <script src="{% static 'perso_admin/js/bootstrap.min.js'%}"></script>
</head>

<body class="g-sidenav-show bg-gray-100">
  <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
        <span class="ms-1 font-weight-bold text-white">Suivi Livraison.</span><i class="fas fa-paper-plane bg-white rounded-pill p-2 mx-3 " style="font-size: 20px; color: red; position: relative; top: 10px;"></i>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse w-auto" id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'perso_admin:dashboard' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-chart-line"></span>
            </div>
            <span class="nav-link-text ms-1">Tableau de bord</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'app_utilisateur:profil' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-user-circle"></span>
            </div>
            <span class="nav-link-text ms-1">Mon profil</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'perso_admin:menu'%}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-people-group"></span>
            </div>
            <span class="nav-link-text ms-1">Administrateurs</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'colis:menu'%}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-cube"></span>
            </div>
            <span class="nav-link-text ms-1">Colis</span>
          </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'Livraison:menu' %}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <span class="fas fa-truck-fast"></span>
              </div>
              <span class="nav-link-text ms-1">Livraisons</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'app_utilisateur:menu' %}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <span class="fas fa-users"></span>
              </div>
              <span class="nav-link-text ms-1">Utilisateurs</span>
            </a>
          </li>
        <div style="border-top: 1px solid white;"></div>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'perso_admin:logout' %}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <span class="fas fa-power-off"></span>
            </div>
            <span class="nav-link-text ms-1">Deconnexion</span>
          </a>
        </li>
      </ul>
    </div>
  </aside>  
  <main class="main-content border-radius-lg">
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur"
      data-scroll="true">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark font-weight-bolder" aria-current="page">Supprissionn d'Administrateur</li>
          </ol>
          <h6 class="font-weight-bolder mb-0">Supprimer un Administrateur</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <div class="input-group input-group-outline">
              <input type="text" class="form-control" id="searchInput" placeholder="Recherche">
            </div>
          </div>
          <ul class="navbar-nav justify-content-end">
            <li class="nav-item d-flex align-items-center">
              <a class="btn btn-outline-primary btn-sm mb-0 me-3" href="{% url 'app_utilisateur:profil'%}" data-toggle="tooltip" data-placement="bottom" title="Mon profil"> <span class="fas fa-user-circle"></span></a>
            </li>
            <li class="nav-item d-flex align-items-center">
              <a class="btn btn-outline-primary btn-sm mb-0 me-3" href="{% url 'perso_admin:logout'%}" data-toggle="tooltip" data-placement="bottom" title="Se deconnecter"> <span class="fas fa-power-off"></span></a>
            </li>
            <!-- Add more navbar items here -->
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid py-4">
      <div class="row">
        <div class="container ">
          <div class="row mb-3">
            <div class="col-md-6">
              <div class="d-flex flex-column justify-content-center">
                <h1 class="mb-0 text-sm"> Suppression
                </h1>
                <p class="text-xs text-secondary mb-0">
                  
                </p>
              </div>
            </div>
            <div class="col-md-6">
              <p class="text-xs font-weight-bold mb-0">
              </p>

            </div>
          </div>
          <div class="col-12">
            <div class="card mb-4">
              <div class="card-header pb-0">
                <h6>Supprimer des administrateurs</h6>
              </div>
              <div class="card-body px-3 pt-3 pb-2">
                <p>Êtes-vous sûr de vouloir supprimer l'administrateur suivant :</p>
                <p>Nom : {{ admin.username }}</p>
                <p>Email : {{ admin.email }}</p>
                <form method="POST" action="{% url 'perso_admin:delete_admin' %}">
                    <input type="hidden" name="admin_id" value="{{ admin.id }}">
                    <div class="container">
                      <div class="row">
                        <div class="col-md-6">
                          <button type="submit" class="btn btn-danger form-control "><span class="fas fa-trash-can"></span> Supprimer</button>
    
                        </div>
                        <div class="col-md-6">
                          <a href="{% url 'perso_admin:menu' %}" class="btn btn-secondary form-control"><span class=" fas fa-arrow-right-from-bracket"></span> Annuler Annuler</a>
    
                        </div>
                      </div>
                    </div>

                </form>

              <div id="paginationE" class="mt-3 mx-3">
                  <span class="px-3" id="pagination"></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <script src="{% static 'perso_admin/js/script.js'%}">


  </script>
  <!-- Edit Admin Modal -->
  <div class="modal fade" id="editAdminModal" tabindex="-1" role="dialog" aria-labelledby="editAdminModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editAdminModalLabel">Consulter un Administrateur</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  </div>

</body>

</html>